server:
  port: 8099

spring:
  config:
    activate:
      on-profile: dev
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:1b
          temperature: 0.7

theatre:
  reservation-hold-minutes: 15
  default-page-size: 10
  log-level: INFO
  log-file: logs/theatre.log

logging:
  level:
    root: WARN
    bg.uni.fmi.theatre: INFO