spring:
  application:
    name: theatre-ticketing
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=theatre
    username: theatre
    password: theatre
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: theatre
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: theatre

server:
  port: 8099

theatre:
  reservation-hold-minutes: 15
  default-page-size: 10
  log-level: INFO
  log-file: logs/theatre.log

logging:
  level:
    root: WARN
    bg.uni.fmi.theatre: INFO
